name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build_luajit:
    name: Test on LuaJIT
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [tags/v2.0.5, tags/v2.1.0-beta3, heads/v2.1]

    steps:
      - name: Build LuaJIT ${{ matrix.version }}
        env:
          LUAJIT_VERSION: ${{ matrix.version }}
          LSAN_OPTIONS: exitcode=0
        run: |
          wget "https://github.com/LuaJIT/LuaJIT/archive/refs/${LUAJIT_VERSION}.tar.gz" -O luajit.tar.gz
          mkdir -p LuaJIT
          tar xzvf luajit.tar.gz -C ./LuaJIT --strip-components=1
          cd LuaJIT
          make CC='gcc -g'
      - name: Install LuaJIT ${{ matrix.version }}
        env:
          LUAJIT_VERSION: ${{ matrix.version }}
        run: |
          cd LuaJIT
          sudo make install
          sudo ln -frs /usr/local/bin/luajit-* /usr/local/bin/lua
          sudo ln -frs /usr/local/lib/libluajit-*.a /usr/local/lib/liblua.a
          sudo ln -frs /usr/local/include/luajit-*/* /usr/local/include/
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: source .github/install_deps.bash
      - name: Build lgi and the test suite
        run: |
          make CC='gcc -g -fsanitize=address -fsanitize=undefined -ftest-coverage -fprofile-arcs'
          make -C tests CC='gcc -g -fsanitize=address -fsanitize=undefined -ftest-coverage -fprofile-arcs' LUA_LIB='-llua -ldl -lm'
      - name: Run tests
        env:
          LSAN_OPTIONS: suppressions=${{ github.workspace }}/.github/lsan.supp
          UBSAN_OPTIONS: print_stacktrace=1:report_error_type=1:halt_on_error=1:suppressions=${{ github.workspace }}/.github/ubsan.supp
        run: |
          source .github/find_asan_ubsan.bash "lgi/corelgilua51.so"
          xvfb-run -a sh -c 'LD_PRELOAD="${sanitizers}" make check'
      - name: Check that make install works
        env:
          LSAN_OPTIONS: suppressions=${{ github.workspace }}/.github/lsan.supp
          UBSAN_OPTIONS: print_stacktrace=1:report_error_type=1:halt_on_error=1:suppressions=${{ github.workspace }}/.github/ubsan.supp
          LUA_VERSION: ${{ matrix.version }}
        run: |
          source .github/find_asan_ubsan.bash "lgi/corelgilua51.so"
          source .github/test_make_install.bash
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v1
